version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-toggle
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "TOGGLE"
    volumes:
      - app_volumes:/var/lib/postgres

volumes:
  app_volumes:


